### ISSUE TITLE
Dependency install issues

### ISSUE THREAD

**Issue by cpheinrich** [indianajohn/web-geo-viewer#2]
Running 
```
rustup target add wasm32-unknown-unknown --toolchain nightly
```
thows the error
```
error: toolchain 'nightly-x86_64-apple-darwin' is not installed
```

on Mac OS 10.15.4. However running:

```
rustup target add wasm32-unknown-unknown
```
worked. 

Does it hurt to remove the `--toolchain nightly` ?

**Comment by indianajohn** [comment]
Nightly rust is recommended for a lot of crates because stable lacks a lot of features that nightly does not. A lot of crates specifically target nightly.

It's very possible that this builds on stable, but it's kind of loose "best practice" to use nightly in the Rust ecosystem. Less often these days.

To install and use nightly you'd run:

```
rustup toolchain install nightly
```

And then the command you ran would work. I'll add some clarification to the README.md about this.

**Comment by cpheinrich** [comment]
Thanks, --toolchain nightly worked for me after running this command
